services:
  pg-db:
    image: postgres
    restart: always
    container_name: pg-db
    hostname: pg-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ashPassword} # the username is postgres
    volumes:
      - ./databases:/usr/databases

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-ash@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD:-ashPassword}"
    volumes:
      - ./databases:/usr/databases
    restart: always
    ports:
      - "5050:80"
