services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    hostname: fastapi
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - pg-db

  pg-db:
    image: postgres
    restart: always
    container_name: pg-db
    hostname: pg-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ashPassword} # the username is postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-ash@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD:-ashPassword}"
    volumes:
      - ./databases:/usr/databases
    restart: always
    ports:
      - "5050:80"

volumes:
  postgres-data:
